### ISSUE TITLE
Car cant make it very far

### ISSUE THREAD

**Issue by kelevra69** [ChrisToFLuA/tofmechanicAI#1]
Not sure if there is a setting or what is the fix or adjustment but if we drive cars from city to sandy they break down before getting there....is there a way to adjust when the break down is

**Comment by ChrisToFLuA** [comment]
do you use a script like realisticvehiclefailure ?

**Comment by kelevra69** [comment]
Yes we are....is there settings there that are playing into this? if so do you have some suggestions on what settings should be?

**Comment by ChrisToFLuA** [comment]
this is this script who manage vehicle damage, not simple to configure, need a lot of tests.

**Comment by kelevra69** [comment]
ok cool...on another note is there a way to take out the message that pops up for what to type for mechanic?

**Comment by ChrisToFLuA** [comment]
i will put it as an option yes
